[build]
  base = "client"               # This tells Netlify to run commands from the 'client' folder
  command = "npm install && npm run build"  # Always install dependencies before building
  publish = "client/.next"      # For Netlify to know where the output is

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
